# Q1

In [13]:
import numpy as np
array = np.arange(2,50,3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Q2

In [2]:
lst = [] 
n1 = int(input("Enter number of elements : ")) 
for i in range(0, n1): 
    ele = int(input()) 
  
    lst.append(ele)  
      
print(lst) 

list2 = [] 
n = int(input("Enter number of elements : ")) 
for i in range(0, n): 
    elem = int(input()) 
  
    list2.append(elem) 
print(list2) 

import numpy as np
arr1 = np.array(lst)
arr2 = np.array(list2)
a1 = np.concatenate((arr1,arr2), axis = None)
a2 = np.sort(a1)
print(a2)

Enter number of elements : 5
5
8
9
10
23
[5, 8, 9, 10, 23]
Enter number of elements : 5
20
14
12
17
5
[20, 14, 12, 17, 5]
[ 5  5  8  9 10 12 14 17 20 23]


# Q3

In [9]:
import numpy as np

#dimensions
a_1_d = np.arange(3)
print(a_1_d)
#printing the dim
print(a_1_d.ndim)

[0 1 2]
1


In [10]:
a_2_d = np.arange(12).reshape((3, 4))
print(a_2_d)
#printing the dim
print(a_2_d.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [12]:
#printing the size
print(a_1_d.size)
print(a_2_d.size)

3
12


# Q4

In [16]:
a = np.arange(3)
print(a)

[0 1 2]


In [19]:
#adding a new dimension
print(a[:, np.newaxis])

[[0]
 [1]
 [2]]


# Q5

In [3]:
import numpy as np
a = np.array([1,3,5])
b = np.array([7,9,11])
np.vstack((a, b))


array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a, b))


array([1, 2, 3, 4, 5, 6])

# Q5

In [5]:
import numpy as np
a = [3,5,8,2,5,8]
x = np.array(a)
print(np.unique(a))

[2 3 5 8]


In [8]:
import numpy as np
a = [3,5,8,2,5,8]
x = np.array(a)
print(np.unique(a, return_counts = True))

(array([2, 3, 5, 8]), array([1, 1, 2, 2], dtype=int64))
